### ISSUE TITLE
Add flavors.

### ISSUE THREAD

**Issue by apomalyn** [apomalyn/mangadex-app#4]
Because we are still in an early stage of development it will be easier to add flavours to the project.

## Tasks

- [x] Design custom icon for dev flavour
- [x] Design custom icon for beta flavour
- [x] Implement dev flavour with custom icon
- [x] Implement beta flavour with custom icon
- [x] Implement production flavour
